[package]
name = "dir-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dir-test-macros = { version = "0.1.0", path = "../macros"  }